const TOGGLE_START = "TOGGLE_START";
const TOGGLE_QUIT = "TOGGLE_QUIT";

const SET_LEVELS = "SET_LEVELS";
const CLEAR_LEVELS = "CLEAR_LEVELS";

export default { TOGGLE_START, TOGGLE_QUIT, SET_LEVELS, CLEAR_LEVELS };
