const TOGGLE_START = "TOGGLE_START";
const SET_ERROR = "SET_ERROR";
const SET_FLIPPED = "SET_FLIPPED";
const RESET_FLIPPED = "RESET_FLIPPED";
const SET_SOLVED = "SET_SOLVED";
const RESET_SOLVED = "RESET_SOLVED";
const TO_COMPARE = "TO_COMPARE";
const RESET_COMPARE = "RESET_COMPARE";
const SET_REGISTER = "SET_REGISTER";
const SET_isLogged = "SET_ISLOGGED";

export default {
  TOGGLE_START,
  SET_ERROR,
  SET_FLIPPED,
  RESET_FLIPPED,
  SET_SOLVED,
  RESET_SOLVED,
  TO_COMPARE,
  RESET_COMPARE,
  SET_REGISTER,
  SET_isLogged
};
