const SET_NICK = "SET_NICK";
const CLEAR_NICK = "CLEAR_NICK";
const SET_TIME = "SET_TIME";
const INCREASE_STEP = "INCREASE_STEP";
const RESET_STEP = "RESET_STEP";
const SET_LEVELS = "SET_LEVELS";
const CLEAR_LEVELS = "CLEAR_LEVELS";

export default {
  SET_NICK,
  CLEAR_NICK,
  SET_TIME,
  INCREASE_STEP,
  RESET_STEP,
  SET_LEVELS,
  CLEAR_LEVELS
};
