const SET_VALUE = "SET_VALUE";
const CLEAR_FIELDS = "CLEAR_FIELDS";
const TOGGLE_START = "TOGGLE_START";
const TOGGLE_QUIT = "TOGGLE_QUIT";
const INCREASE_STEP = "INCREASE_STEP";
const RESET_STEP = "RESET_STEP";
const SET_FLIPPED = "SET_FLIPPED";
const RESET_FLIPPED = "RESET_FLIPPED";
const SET_SOLVED = "SET_SOLVED";
const RESET_SOLVED = "RESET_SOLVED";
const TO_COMPARE = "TO_COMPARE";
const RESET_COMPARE = "RESET_COMPARE";
const SET_ERROR = "SET_ERROR";

export default {
  SET_VALUE,
  CLEAR_FIELDS,
  TOGGLE_START,
  TOGGLE_QUIT,
  INCREASE_STEP,
  RESET_STEP,
  SET_FLIPPED,
  RESET_FLIPPED,
  SET_SOLVED,
  RESET_SOLVED,
  TO_COMPARE,
  RESET_COMPARE,
  SET_ERROR
};
